export const EVENTS = {
  RENTAL_CREATED: 'RENTAL_CREATED',
  RENTAL_RETURNED: 'RENTAL_RETURNED',
  RENTAL_EXPIRED: 'RENTAL_EXPIRED',
  PURCHASE_COMPLETED: 'PURCHASE_COMPLETED',
  PURCHASE_REFUNDED: 'PURCHASE_REFUNDED',
} as const;

export type EventType = (typeof EVENTS)[keyof typeof EVENTS];
